import './globals.css';

import type { Metadata } from 'next';
import Head from 'next/head';

export const metadata: Metadata = {
  title: 'AJ Bell funds - Investment Strategy Selector',
  description: 'Select and compare investment funds - Generated by JKL',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
      </Head>
      <body className="bg-gradient-to-r from-blue-950 via-blue-900 to-blue-950 p-4 antialiased">
        {children}
      </body>
    </html>
  );
}
