import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'AJ Bell funds - Investment Strategy Selector',
  description: 'Select and compare investment funds - Generated by JKL',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta charSet="utf-8" />
      </head>
      <body className="antialiased bg-gradient-to-r from-blue-950 via-blue-900 to-blue-950 p-4">
        {children}
      </body>
    </html>
  );
}
